# Generated by Django 4.1.4 on 2022-12-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_new_phone_user_otp_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cource',
            old_name='name',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='cource',
            old_name='description_en',
            new_name='description_kril',
        ),
        migrations.RenameField(
            model_name='cource',
            old_name='description_ru',
            new_name='description_lat',
        ),
        migrations.RemoveField(
            model_name='cource',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='cource',
            name='lang',
        ),
        migrations.AddField(
            model_name='cource',
            name='name_kril',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cource',
            name='name_lat',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cource',
            name='test_channel',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
