# Generated by Django 4.1.4 on 2022-12-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_name_cource_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cource',
            name='price_12_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cource',
            name='price_3_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cource',
            name='price_6_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cource',
            name='price_9_month',
            field=models.IntegerField(default=0),
        ),
    ]
