# Generated by Django 4.1.4 on 2022-12-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_cource_price_12_month_cource_price_3_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
