# Generated by Django 4.1.4 on 2023-01-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_comment_faq_slider_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='cource',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
